name: PR CI - Lint Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install linter
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8 linter
        run: |
          echo "Running flake8 on your code..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
