name: PR CI - Lint Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: echo "Successfully pre-merge tests done!"
